@HostAddress = http://localhost:5053

###

# with-query-string : 200 OK - valid
GET {{HostAddress}}/with-query-string/
    ?requiredString=value
    &requiredRangedInt=1 
Accept: application/json

###

# with-query-string : 200 OK - valid with optional
GET {{HostAddress}}/with-query-string/
    ?requiredString=value
    &optionalRangedInt=optional
    &requiredRangedInt=1
    &optionalRangedInt=6
Accept: application/json

###

# with-query-string : 400 BAD REQUEST  - missing required
GET {{HostAddress}}/with-query-string/
    ?requiredString=value
Accept: application/json

###

# with-query-string : 400 BAD REQUEST  - missing all required
GET {{HostAddress}}/with-query-string/
Accept: application/json

###

# with-query-string : 400 BAD REQUEST  - out of range
GET {{HostAddress}}/with-query-string/
    ?requiredString=value
    &requiredRangedInt=0
Accept: application/json

###

# with-query-group : 200 OK - valid
GET {{HostAddress}}/with-query-group/
    ?name=bilbo
    &age=111
    &other=abc
Accept: application/json

###

# with-query-group : 400 BAD REQUEST - age out of range
GET {{HostAddress}}/with-query-group/
    ?name=bilbo
    &age=200
    &other=abc
Accept: application/json
