@HostAddress = http://localhost:5053

###

# with-headers : 200 OK - valid
GET {{HostAddress}}/with-headers/
Accept: application/json
x-required: value
x-required-int-with-range: 5

###

# with-headers : 200 OK  - valid with optional
GET {{HostAddress}}/with-headers/
Accept: application/json
x-required: value
x-optional: value
x-required-int-with-range: 5
x-optional-int-with-range: 9

###

# with-headers : 400 BAD REQUEST  - missing required
GET {{HostAddress}}/with-headers/
Accept: application/json
x-optional: value
x-required-int-with-range: 5
x-optional-int-with-range: 9

###

# with-headers : 400 BAD REQUEST  - missing both required
GET {{HostAddress}}/with-headers/
Accept: application/json
x-optional: value
x-optional-int-with-range: 9

###

# with-headers : 400 BAD REQUEST  - out of range
GET {{HostAddress}}/with-headers/
Accept: application/json
x-required: value
x-optional: value
x-required-int-with-range: 0
x-optional-int-with-range: 1
